In [11]:
import pyarrow.parquet as pq
import pyarrow as pa
import pandas as pd
from pathlib import Path

In [13]:

cwd_dir = Path.cwd() #For running locally
base_dir = cwd_dir.parent
data_dir= base_dir / 'data' /'simulated_health_data' / 'data'

In [14]:
df=pd.read_csv(data_dir / 'withtimeseries-10-100-10-5-2-True-10-5-2-True-2-101-5-0-0.csv')
df

,person_id,yyyymm,cad0,cad1,cad2,cad3,cad4,cad5,cad6,cad7,...,dv4,dv5,dv6,dv7,dv8,dv9,target_bin,target_class,target,index_c
0,1000,201701,1,1,1,1,1,1,1,1,...,0.651118,-0.319318,-0.848077,0.605965,-2.018168,0.740122,1,1,305.032212,0
1,1000,201702,1,1,1,1,1,1,1,1,...,0.651118,-0.319318,-0.848077,0.605965,-2.018168,0.740122,1,1,305.032212,0
2,1000,201703,1,1,1,1,1,1,1,1,...,0.651118,-0.319318,-0.848077,0.605965,-2.018168,0.740122,1,1,305.032212,0
3,1000,201704,1,1,1,1,1,1,1,1,...,0.651118,-0.319318,-0.848077,0.605965,-2.018168,0.740122,1,1,305.032212,0
4,1000,201705,1,1,1,1,1,1,1,1,...,0.651118,-0.319318,-0.848077,0.605965,-2.018168,0.740122,1,1,305.032212,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215995,9999,201808,1,1,1,0,0,0,0,0,...,0.487144,-0.686401,-0.218947,0.273039,0.011350,-0.370388,0,0,-27.788632,99
215996,9999,201809,1,1,1,0,0,0,0,0,...,0.487144,-0.686401,-0.218947,0.273039,0.011350,-0.370388,0,0,-27.788632,99
215997,9999,201810,1,1,1,0,0,0,0,0,...,0.487144,-0.686401,-0.218947,0.273039,0.011350,-0.370388,0,0,-27.788632,99
215998,9999,201811,1,1,1,0,0,0,0,0,...,0.487144,-0.686401,-0.218947,0.273039,0.011350,-0.370388,0,0,-27.788632,99
215999,9999,201812,1,1,1,0,0,0,0,0,...,0.487144,-0.686401,-0.218947,0.273039,0.011350,-0.370388,0,0,-27.788632,99

In [15]:
table = pa.Table.from_pandas(df, preserve_index=False)

In [16]:
pq.write_table(table, data_dir /'withtimeseries-10-100-10-5-2-True-10-5-2-True-2-101-5-0-0.parquet')

In [19]:
#write to dataset without partition
pq.write_to_dataset(table, root_path= str(data_dir / 'dataset_new'))

In [21]:
parquet_file = pq.ParquetFile( data_dir /'withtimeseries-10-100-10-5-2-True-10-5-2-True-2-101-5-0-0.parquet')

In [22]:
parquet_file.metadata

<pyarrow._parquet.FileMetaData object at 0x7fb490438b30>
  created_by: parquet-cpp version 1.5.1-SNAPSHOT
  num_columns: 27
  num_rows: 216000
  num_row_groups: 1
  format_version: 1.0
  serialized_size: 11950

In [23]:
parquet_file.schema

<pyarrow._parquet.ParquetSchema object at 0x7fb490437b90>
person_id: INT64
yyyymm: INT64
cad0: INT64
cad1: INT64
cad2: INT64
cad3: INT64
cad4: INT64
cad5: INT64
cad6: INT64
cad7: INT64
cad8: INT64
cad9: INT64
cadre: INT64
dv0: DOUBLE
dv1: DOUBLE
dv2: DOUBLE
dv3: DOUBLE
dv4: DOUBLE
dv5: DOUBLE
dv6: DOUBLE
dv7: DOUBLE
dv8: DOUBLE
dv9: DOUBLE
target_bin: INT64
target_class: INT64
target: DOUBLE
index_c: INT64

In [ ]:
parquet_file = pq.ParquetFile('..data/simulated_health_data/example.parquet')